In [1]:
import torch

In [2]:
from env import TicTacToe
from agent import AgentPPO, RandomAgent
import os
import numpy as np

In [3]:
def simulate_game(agent: AgentPPO, opp: RandomAgent, env: TicTacToe):
    # total_players = [agent, opp]
    cur_player_index = np.random.randint(0, 2)
    state = env.get_initial_state()

    while True:
        cur_player_index = cur_player_index % 2
        if cur_player_index == 0:
            availalbe_action = env.get_valid_moves(state)
            action = agent.act(env.get_encoded_single_state(state), availalbe_action)
            next_state = env.get_next_state(state, action)
            reward, is_terminated = env.get_value_and_terminated(next_state, action)

            if is_terminated:
                return reward

        else:
            availalbe_action = env.get_valid_moves(state)
            action = opp.act(state, availalbe_action)
            next_state = env.get_next_state(state, action)
            reward, is_terminated = env.get_value_and_terminated(next_state, action)
            if is_terminated:
                return -reward

        state = env.reserve_state(next_state)

In [19]:
game = TicTacToe()
random_agent = RandomAgent()
agent = AgentPPO(game.get_state_size(), game.action_size)
folder_path = "checkpoint"
all_files = [
    f for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))
]

all_files.sort(key=lambda x: int("".join(filter(str.isdigit, x)) or 0))

test_game = 2000


def simulate_game(agent: AgentPPO, opp: RandomAgent, env: TicTacToe):
    # total_players = [agent, opp]
    cur_player_index = np.random.randint(0, 2)
    state = env.get_initial_state()

    while True:
        cur_player_index = cur_player_index % 2
        if cur_player_index == 0:
            availalbe_action = env.get_valid_moves(state)
            action = agent.act(env.get_encoded_single_state(state), availalbe_action)
            next_state = env.get_next_state(state, action)
            reward, is_terminated = env.get_value_and_terminated(next_state, action)

            if is_terminated:
                return reward

        else:
            availalbe_action = env.get_valid_moves(state)
            action = opp.act(state, availalbe_action)
            next_state = env.get_next_state(state, action)
            reward, is_terminated = env.get_value_and_terminated(next_state, action)
            if is_terminated:
                return -reward

        cur_player_index += 1

        state = env.reserve_state(next_state)


for f in all_files:
    agent = AgentPPO(game.get_state_size(), game.action_size)
    agent.load(f"{folder_path}/{f}")
    result = 0
    for i in range(test_game):
        result += simulate_game(agent, random_agent, game)

    print(f"Agent {f} perform {result}")

Agent 100.pt perform 1207
Agent 200.pt perform 1556
Agent 300.pt perform 1552
Agent 400.pt perform 1597
Agent 500.pt perform 1630
Agent 600.pt perform 1606
Agent 700.pt perform 1612
Agent 800.pt perform 1639
Agent 900.pt perform 1622
Agent 1000.pt perform 1677
Agent 1100.pt perform 1815
Agent 1200.pt perform 1819
Agent 1300.pt perform 1793


In [17]:
agent = AgentPPO(game.get_state_size(), game.action_size)
agent.load(f"checkpoint/1100.pt")


player = -1
state = game.get_initial_state()

while True:
    print(state)

    if player == 1:
        valid_moves = game.get_valid_moves(state)
        # row = int(input(f"Row:"))
        # column = int(input(f"Column:"))

        # action = row * game.row_count + column
        action = int(input(f"Action:"))

        if valid_moves[action] == 0:
            print("action not valid")
            continue

    else:
        bot_state = game.reserve_state(state)
        valids_move = game.get_valid_moves(bot_state)
        action = agent.act(game.get_encoded_single_state(bot_state), valids_move)

    state = game.get_next_state(state, action, player)

    value, is_terminal = game.get_value_and_terminated(state, action)

    if is_terminal:
        print(state)
        if value == 1:
            print(player, "won")
        else:
            print("draw")
        break

    player = -player

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 0.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  0.]]
action not valid
[[ 0.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  0.]]
[[ 0.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]
[[ 0.  0.  0.]
 [ 0. -1. -1.]
 [ 0.  0.  1.]]
action not valid
[[ 0.  0.  0.]
 [ 0. -1. -1.]
 [ 0.  0.  1.]]
action not valid
[[ 0.  0.  0.]
 [ 0. -1. -1.]
 [ 0.  0.  1.]]
[[ 0.  0.  0.]
 [ 1. -1. -1.]
 [ 0.  0.  1.]]
[[-1.  0.  0.]
 [ 1. -1. -1.]
 [ 0.  0.  1.]]
[[-1.  1.  0.]
 [ 1. -1. -1.]
 [ 0.  0.  1.]]
[[-1.  1.  0.]
 [ 1. -1. -1.]
 [-1.  0.  1.]]
[[-1.  1.  0.]
 [ 1. -1. -1.]
 [-1.  1.  1.]]
[[-1.  1. -1.]
 [ 1. -1. -1.]
 [-1.  1.  1.]]
-1 won


In [11]:
agent = AgentDQN(game.get_state_size(), game.action_size)
agent.load(f"checkpoints/1000.pth")

player = 1
state = game.get_initial_state()

while True:
    print(state)

    if player == 1:
        valid_moves = game.get_valid_moves(state)
        # row = int(input(f"Row:"))
        # column = int(input(f"Column:"))

        # action = row * game.row_count + column
        action = int(input(f"Action:"))

        if valid_moves[action] == 0:
            print("action not valid")
            continue

    else:
        bot_state = game.reserve_state(state)
        valids_move = game.get_valid_moves(bot_state)
        action = agent.act(game.get_encoded_state(bot_state), valids_move)

    state = game.get_next_state(state, action, player)

    value, is_terminal = game.get_value_and_terminated(state, action)

    if is_terminal:
        print(state)
        if value == 1:
            print(player, "won")
        else:
            print("draw")
        break

    player = -player

Models loaded from checkpoints/1000.pth
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[-1.  1.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[-1.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]]
[[-1.  1.  0.]
 [ 0.  1.  0.]
 [-1.  0.  0.]]
[[-1.  1.  0.]
 [ 0.  1.  0.]
 [-1.  1.  0.]]
1 won
