In [26]:
import torch

In [27]:
from env import TicTacToe
from agent import AgentPPO, RandomAgent
import os
import numpy as np

In [28]:
def simulate_game(agent: AgentPPO, opp: RandomAgent, env: TicTacToe):
    # total_players = [agent, opp]
    cur_player_index = np.random.randint(0, 2)
    state = env.get_initial_state()

    while True:
        cur_player_index = cur_player_index % 2
        if cur_player_index == 0:
            availalbe_action = env.get_valid_moves(state)
            action = agent.act(env.get_encoded_single_state(state), availalbe_action)
            next_state = env.get_next_state(state, action)
            reward, is_terminated = env.get_value_and_terminated(next_state, action)

            if is_terminated:
                return reward

        else:
            availalbe_action = env.get_valid_moves(state)
            action = opp.act(state, availalbe_action)
            next_state = env.get_next_state(state, action)
            reward, is_terminated = env.get_value_and_terminated(next_state, action)
            if is_terminated:
                return -reward

        state = env.reserve_state(next_state)

In [29]:
game = TicTacToe()
random_agent = RandomAgent()
agent = AgentPPO(game.get_state_size(), game.action_size)
folder_path = "checkpoint"
all_files = [
    f for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))
]

all_files.sort(key=lambda x: int("".join(filter(str.isdigit, x)) or 0))

test_game = 1000


def simulate_game(agent: AgentPPO, opp: RandomAgent, env: TicTacToe):
    # total_players = [agent, opp]
    cur_player_index = np.random.randint(0, 2)
    state = env.get_initial_state()

    while True:
        cur_player_index = cur_player_index % 2
        if cur_player_index == 0:
            availalbe_action = env.get_valid_moves(state)
            action = agent.act(env.get_encoded_single_state(state), availalbe_action)
            next_state = env.get_next_state(state, action)
            reward, is_terminated = env.get_value_and_terminated(next_state, action)

            if is_terminated:
                return reward

        else:
            availalbe_action = env.get_valid_moves(state)
            action = opp.act(state, availalbe_action)
            next_state = env.get_next_state(state, action)
            reward, is_terminated = env.get_value_and_terminated(next_state, action)
            if is_terminated:
                return -reward

        cur_player_index += 1

        state = env.reserve_state(next_state)


for f in all_files:
    agent = AgentPPO(game.get_state_size(), game.action_size)
    agent.load(f"{folder_path}/{f}")
    result = 0
    for i in range(test_game):
        result += simulate_game(agent, random_agent, game)

    print(f"Agent {f} perform {result}")

Model loaded from checkpoint/0.pt
Agent 0.pt perform 21
Model loaded from checkpoint/5.pt
Agent 5.pt perform -32
Model loaded from checkpoint/10.pt
Agent 10.pt perform 61
Model loaded from checkpoint/15.pt
Agent 15.pt perform 79
Model loaded from checkpoint/20.pt
Agent 20.pt perform 77
Model loaded from checkpoint/25.pt
Agent 25.pt perform 268
Model loaded from checkpoint/30.pt
Agent 30.pt perform 306
Model loaded from checkpoint/35.pt
Agent 35.pt perform 337
Model loaded from checkpoint/40.pt
Agent 40.pt perform 373
Model loaded from checkpoint/45.pt
Agent 45.pt perform 389
Model loaded from checkpoint/50.pt
Agent 50.pt perform 414
Model loaded from checkpoint/55.pt
Agent 55.pt perform 469
Model loaded from checkpoint/60.pt
Agent 60.pt perform 539
Model loaded from checkpoint/65.pt
Agent 65.pt perform 542
Model loaded from checkpoint/70.pt
Agent 70.pt perform 556
Model loaded from checkpoint/75.pt
Agent 75.pt perform 542
Model loaded from checkpoint/80.pt
Agent 80.pt perform 561
Model

In [30]:
agent = AgentPPO(game.get_state_size(), game.action_size)
agent.load(f"checkpoint/195.pt")


player = 1
state = game.get_initial_state()

while True:
    print(state)

    if player == 1:
        valid_moves = game.get_valid_moves(state)
        # row = int(input(f"Row:"))
        # column = int(input(f"Column:"))

        # action = row * game.row_count + column
        action = int(input(f"Action:"))

        if valid_moves[action] == 0:
            print("action not valid")
            continue

    else:
        bot_state = game.reserve_state(state)
        valids_move = game.get_valid_moves(bot_state)
        action = agent.act(game.get_encoded_single_state(bot_state), valids_move)

    state = game.get_next_state(state, action, player)

    value, is_terminal = game.get_value_and_terminated(state, action)

    if is_terminal:
        print(state)
        if value == 1:
            print(player, "won")
        else:
            print("draw")
        break

    player = -player

Model loaded from checkpoint/195.pt
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 0.  1.  0.]
 [ 0.  0.  0.]
 [ 0. -1.  0.]]
[[ 1.  1.  0.]
 [ 0.  0.  0.]
 [ 0. -1.  0.]]
[[ 1.  1.  0.]
 [ 0.  0.  0.]
 [ 0. -1. -1.]]
[[ 1.  1.  0.]
 [ 1.  0.  0.]
 [ 0. -1. -1.]]
[[ 1.  1.  0.]
 [ 1.  0.  0.]
 [-1. -1. -1.]]
-1 won


In [11]:
agent = AgentDQN(game.get_state_size(), game.action_size)
agent.load(f"checkpoints/1000.pth")

player = 1
state = game.get_initial_state()

while True:
    print(state)

    if player == 1:
        valid_moves = game.get_valid_moves(state)
        # row = int(input(f"Row:"))
        # column = int(input(f"Column:"))

        # action = row * game.row_count + column
        action = int(input(f"Action:"))

        if valid_moves[action] == 0:
            print("action not valid")
            continue

    else:
        bot_state = game.reserve_state(state)
        valids_move = game.get_valid_moves(bot_state)
        action = agent.act(game.get_encoded_state(bot_state), valids_move)

    state = game.get_next_state(state, action, player)

    value, is_terminal = game.get_value_and_terminated(state, action)

    if is_terminal:
        print(state)
        if value == 1:
            print(player, "won")
        else:
            print("draw")
        break

    player = -player

Models loaded from checkpoints/1000.pth
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[-1.  1.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[-1.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]]
[[-1.  1.  0.]
 [ 0.  1.  0.]
 [-1.  0.  0.]]
[[-1.  1.  0.]
 [ 0.  1.  0.]
 [-1.  1.  0.]]
1 won
