In [1]:
import torch

In [2]:
from env import TicTacToe
from agent import AgentPPO, RandomAgent
import os
import numpy as np

In [3]:
def simulate_game(agent: AgentPPO, opp: RandomAgent, env: TicTacToe):
    # total_players = [agent, opp]
    cur_player_index = np.random.randint(0, 2)
    state = env.get_initial_state()

    while True:
        cur_player_index = cur_player_index % 2
        if cur_player_index == 0:
            availalbe_action = env.get_valid_moves(state)
            action = agent.act(env.get_encoded_single_state(state), availalbe_action)
            next_state = env.get_next_state(state, action)
            reward, is_terminated = env.get_value_and_terminated(next_state, action)

            if is_terminated:
                return reward

        else:
            availalbe_action = env.get_valid_moves(state)
            action = opp.act(state, availalbe_action)
            next_state = env.get_next_state(state, action)
            reward, is_terminated = env.get_value_and_terminated(next_state, action)
            if is_terminated:
                return -reward

        state = env.reserve_state(next_state)

In [11]:
game = TicTacToe()
random_agent = RandomAgent()
agent = AgentPPO(game.get_state_size(), game.action_size)
folder_path = "checkpoint"
all_files = [
    f for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))
]

all_files.sort(key=lambda x: int("".join(filter(str.isdigit, x)) or 0))

test_game = 1000


def simulate_game(agent: AgentPPO, opp: RandomAgent, env: TicTacToe):
    # total_players = [agent, opp]
    cur_player_index = np.random.randint(0, 2)
    state = env.get_initial_state()

    while True:
        cur_player_index = cur_player_index % 2
        if cur_player_index == 0:
            availalbe_action = env.get_valid_moves(state)
            action = agent.act(env.get_encoded_single_state(state), availalbe_action)
            next_state = env.get_next_state(state, action)
            reward, is_terminated = env.get_value_and_terminated(next_state, action)

            if is_terminated:
                return reward

        else:
            availalbe_action = env.get_valid_moves(state)
            action = opp.act(state, availalbe_action)
            next_state = env.get_next_state(state, action)
            reward, is_terminated = env.get_value_and_terminated(next_state, action)
            if is_terminated:
                return -reward

        cur_player_index += 1

        state = env.reserve_state(next_state)


for f in all_files:
    agent = AgentPPO(game.get_state_size(), game.action_size)
    agent.load(f"{folder_path}/{f}")
    result = 0
    for i in range(test_game):
        result += simulate_game(agent, random_agent, game)

    print(f"Agent {f} perform {result}")

Agent 10.pt perform 768
Agent 20.pt perform 778
Agent 30.pt perform 779
Agent 40.pt perform 787
Agent 50.pt perform 770
Agent 60.pt perform 763
Agent 70.pt perform 811
Agent 80.pt perform 801
Agent 90.pt perform 788
Agent 100.pt perform 771
Agent 110.pt perform 795
Agent 120.pt perform 763
Agent 130.pt perform 786
Agent 140.pt perform 825
Agent 150.pt perform 766
Agent 160.pt perform 791
Agent 170.pt perform 795
Agent 180.pt perform 794
Agent 190.pt perform 785
Agent 200.pt perform 795


In [12]:
agent = AgentPPO(game.get_state_size(), game.action_size)
agent.load(f"checkpoint/200.pt")


player = 1
state = game.get_initial_state()

while True:
    print(state)

    if player == 1:
        valid_moves = game.get_valid_moves(state)
        # row = int(input(f"Row:"))
        # column = int(input(f"Column:"))

        # action = row * game.row_count + column
        action = int(input(f"Action:"))

        if valid_moves[action] == 0:
            print("action not valid")
            continue

    else:
        bot_state = game.reserve_state(state)
        valids_move = game.get_valid_moves(bot_state)
        action = agent.act(game.get_encoded_single_state(bot_state), valids_move)

    state = game.get_next_state(state, action, player)

    value, is_terminal = game.get_value_and_terminated(state, action)

    if is_terminal:
        print(state)
        if value == 1:
            print(player, "won")
        else:
            print("draw")
        break

    player = -player

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
[[ 0.  0.  0.]
 [ 0.  1.  0.]
 [-1.  0.  0.]]
[[ 0.  0.  0.]
 [ 0.  1.  0.]
 [-1.  0.  1.]]
[[-1.  0.  0.]
 [ 0.  1.  0.]
 [-1.  0.  1.]]
[[-1.  0.  0.]
 [ 1.  1.  0.]
 [-1.  0.  1.]]
[[-1. -1.  0.]
 [ 1.  1.  0.]
 [-1.  0.  1.]]
action not valid
[[-1. -1.  0.]
 [ 1.  1.  0.]
 [-1.  0.  1.]]
[[-1. -1.  0.]
 [ 1.  1.  1.]
 [-1.  0.  1.]]
1 won


In [11]:
agent = AgentDQN(game.get_state_size(), game.action_size)
agent.load(f"checkpoints/1000.pth")

player = 1
state = game.get_initial_state()

while True:
    print(state)

    if player == 1:
        valid_moves = game.get_valid_moves(state)
        # row = int(input(f"Row:"))
        # column = int(input(f"Column:"))

        # action = row * game.row_count + column
        action = int(input(f"Action:"))

        if valid_moves[action] == 0:
            print("action not valid")
            continue

    else:
        bot_state = game.reserve_state(state)
        valids_move = game.get_valid_moves(bot_state)
        action = agent.act(game.get_encoded_state(bot_state), valids_move)

    state = game.get_next_state(state, action, player)

    value, is_terminal = game.get_value_and_terminated(state, action)

    if is_terminal:
        print(state)
        if value == 1:
            print(player, "won")
        else:
            print("draw")
        break

    player = -player

Models loaded from checkpoints/1000.pth
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[-1.  1.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[-1.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]]
[[-1.  1.  0.]
 [ 0.  1.  0.]
 [-1.  0.  0.]]
[[-1.  1.  0.]
 [ 0.  1.  0.]
 [-1.  1.  0.]]
1 won
